<ul>
    <li><a href="http://magento.loc/women/tops-women/jackets-women.html">Women Jackets</a></li>
    <li><a href="http://magento.loc/men/tops-men/tees-men.html">Men Tees</a></li>
    <li><a href="http://magento.loc/men/bottoms-men/pants-men.html">Men Pants</a></li>
    <li><a href="http://magento.loc/gear/watches.html">Watches</a></li>
    <li><a href="http://magento.loc/gear/bags.html">Bags</a></li>
</ul>
