<img src="<?= $this->getViewFileUrl('Magento_Theme::images/metal-holder.png'); ?>" data-mage-init='{"Magento_Theme/js/extend_widget_zoom":{}}'/>
<img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/y_demonstration.png'); ?>" data-mage-init='{"Magento_Theme/js/extend_widget_zoom":{}}'/>
<img src="<?php echo $block->getViewFileUrl('images/red-sports.png'); ?>" data-mage-init='{"Magento_Theme/js/extend_widget_zoom":{}}'/>
