 <div class="search-toggle">
        <span><i class="fas fas-icons fa-search"></i><?= $escaper->escapeHtml(__('Search')) ?></span>
 </div>
<?= $block->getChildHtml()?>
 <script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.search-toggle').on('click', function () {
                $('.store.search').slideToggle("fast");
            })
        });
    });
</script>
